### ISSUE TITLE
Is it possible to display the author for non-Video post types?

### ISSUE THREAD

**Issue by cherylcolan** [cogdog/splotbox#11]
I am loving my [mixed-use splotbox site](https://gccazctle.com) where people can share helpful videos, but where we also write regular blog posts and have several different authors. One complaint I'm getting is that the text-based posts no longer identify the author. I looked a little closer at the single.php file for the splotbox theme. I see that you're grabbing from the "shared by" field and inserting that information in the "Post Info" tab in the post's footer. I see it on all of our posts where the post type is Video. [Here's an example](https://gccazctle.com/2021/02/23/student-self-assessment-perception-of-grading-learning-replicating-peer/) where the "shared by" field has a value of "CTLE".

Does the Splotbox theme assume all posts are the Video post type? 

What I'd love is that for Standard posts, the "Author Info" tab would return in the post's footer, so that our readers could see who wrote the post and find other posts by the same person. Here's a screenshot of that from the Garfunkel theme demo:
<img width="595" alt="author-info" src="https://user-images.githubusercontent.com/7476839/111193756-c1906400-8577-11eb-8d5b-7c602d0eba30.png">

But (1) I don't have the skill to make that happen, and even if I did, (2) I've got this theme automagically updating and wouldn't want to have to re-edit the splotbox child theme each time an update comes out.

I also don't like my colleague's solution: since she's a fellow admin, she's started going into every Standard post and writing "by Name" at the start of every post. Facepalm. The only other solution I know I can do is just use the Garfunkel theme instead, but then I'll lose the lovely Share feature and the other wonderful work you've done in creating the Splotbox theme.

I know you're a busy person and the work you do on Splotbox is an unpaid labor of love, so I understand if this request is too far out of scope for the theme and won't be happening. Still, it can't hurt to share my use case and hope!

**Comment by cherylcolan** [comment]
Gah! I submitted too soon. I meant to also provide [a link to one of our Standard post types](https://gccazctle.com/2021/03/08/lessons-learned-during-the-pandemic-extending-grace-to-students-and-ourselves/), so you can see we don't get the same info as from a Video post type on the "item info" tab. 

As an alternative to the return of the "Author info" tab, I'd definitely settle for the post author being grabbed and displayed as a hyperlink to other posts by the same author - another task beyond my current skill set.

**Comment by cogdog** [comment]
This is not too complex a thing for me to fix. Until you used the theme, I never imagined mixing in ordinary post types. I can fairly easy make a check to see if it was info submitted via the SPLOT form (because it has specific metadata) and if not, can use the regular metadata that the parent theme does.

Actually this did come up for me in a new site, so it's not a big ask.

I appreciate hearing these situations I did not anticipate, it makes the theme better in the long run.

**Comment by cogdog** [comment]
It has nothing to do with video, the Shared By info comes only if the content is entered via the SPLOT form, it is visible when you edit entries if you enable the editor to see custom fields, and is associated in one called "shared_by"

If you added this as when authoring this "posts" it will show up when published

![add-custom field](https://user-images.githubusercontent.com/463038/111208788-d4636280-8590-11eb-9a19-3481b8a73273.jpg)

![tom](https://user-images.githubusercontent.com/463038/111208816-dcbb9d80-8590-11eb-9347-4c3f0e7c43a7.jpg)

It is trickier to tie them together as an archive, I could perhaps tie a search to that entry, but it would depend on being exactly the same.

Another approach you could do now is to tag your posts by the same author, even with a convention of "@tom_foolery" 

The "author" that you see in Garfunkel draws from having that person as a user account on the site, which SPLOTs do not, the "author" is usually the admin of the site. Your old site had that, which is why those ones work under your "contributors" widget. It would get tricky to cross connect these.

**Comment by cherylcolan** [comment]
I figured we could have blog authors fill in the "Shared by" custom field. If that's the way to go, I'll train folks. But I was hoping I could let Wordpress say who the author is based on who wrote the post instead of trying to teach people something new - they're likely to forget to do it.

**Comment by cherylcolan** [comment]
> I can fairly easy make a check to see if it was info submitted via the SPLOT form (because it has specific metadata) and if not, can use the regular metadata that the parent theme does.

If this is possible, it's my preferred solution over teaching our authors how to enable custom fields and add their name for "Shared by" - unless you're saying that will make the site admin appear to be the author of other people's posts. They do all have user accounts on our site. 

I totally understand not wanting to cross-connect different things. If that were something I could easily figure out how to do, I wouldn't be pestering you here!

**Comment by cogdog** [comment]
Okay, a small change just made to current version 3.81. If you create a post from scratch, there is no custom meta data for `shared_by` it will display instead the display name and archive link for a post's author. So you have a choice now to use either method.

![author-ed](https://user-images.githubusercontent.com/463038/111235365-1783fc80-85b6-11eb-93bd-3f96ed7f6d9c.jpg)

**Comment by cherylcolan** [comment]
Wow! Okay, as soon as WP Pusher catches me up I will check it out. Thank you soooo much. Will post back ASAP. You are just the best, @cogdog <3

**Comment by cherylcolan** [comment]
Huh. It looks like WP Pusher hasn't updated Splotbox since v3.6. I have to sort that out, then I'll report back.

**Comment by cherylcolan** [comment]
Hi @cogdog  -  Just a final update. I had to fiddle around with WP Pusher. I used it to install Splotbox, and had checked Push-to-Deploy box at the time, but for whatever reason, I was stuck on version 3.6 of Splotbox. I ended up switching to Garfunkel, reinstalling Splotbox using WP Pusher, and then finding the "Update theme" button, then reactivated Splotbox, which did get me to Splotbox v3.81. My text post authors have their byline again, and I love that their name links to all their posts. I also love that I don't have to teach everyone how to activate custom fields in the editor and then choose "shared_by" - because as great as my colleagues are, they're not all great at following/remembering instructions like that when they only post once a month or so. I'm really grateful you were willing and able to take on this improvement and that it wasn't too huge an ask. I'm closing the issue!
