### ISSUE TITLE
"Upload a File" missing from SPLOTbox Share form

### ISSUE THREAD

**Issue by dhattwig** [cogdog/splotbox#15]
We've set up another class with SPLOTbox (such a great theme, thank you again!), they've called it Toolkit for Student Success. The [Share Form](https://uwb.ds.lib.uw.edu/toolkitforstudentsuccess/share-it/) is missing the "Upload a File" info, however. I just refreshed the theme with the latest version and it is still a problem. A workaround is to "Check Info," then the upload options appear, but it would be nice to have the upload option back on the main share form. Any suggestions for fixing this one? Thank you!

**Comment by dhattwig** [comment]
It looks like PHP 8.0.25...

**Comment by cogdog** [comment]
I'm still trying! I had no issues with PHP 8 and cannot replicated. I am going to rewrite some parts of the logic there.

Can you let me know what plugins if any you are running there? Just trying to rule out any conflicts.

**Comment by dhattwig** [comment]
Thank you! 

Great question about plugins: Customizer Export/Import, Limit Login Attempts, Widget Importer & Exporter, WordPress Importer, WP All Import. Are any of these needed for SPLOTbox? I could try deleting them if not.

**Comment by cogdog** [comment]
No, those are all okay, I have same running on my sites. No need to change, Stay tuned, thanks for paiences

**Comment by dhattwig** [comment]
We're in the Reclaim hosting environment, if there might be anything there I'm not thinking of? Thanks so much for working on it!

**Comment by cogdog** [comment]
No that’s not an issue, all my sites as well as splot.ca are on Reclaim hosting

**Comment by cogdog** [comment]
There is no technical problem. The issue is that you have 2 different pages created using the sharing form template, the link you sent looks like the form but it not the one SPLOTbox considers the active one.

If you visit https://uwb.ds.lib.uw.edu/toolkitforstudentsuccess/share/ the form works.

You can make https://uwb.ds.lib.uw.edu/toolkitforstudentsuccess/share-it/ the active one by selecting it in the SPLOTbox theme options, your site will list two different pages. Or use the link above and adjust your menus

![page-for-sharing](https://user-images.githubusercontent.com/463038/213898707-81b3a115-3735-483e-b9a3-d4cddcab4801.jpg)

This might be confusing! I had a hard time figuring this one out

**Comment by dhattwig** [comment]
Oh wow, that was it! Thank you so very much for taking the time to figure this out for us! I truly appreciate it -
