### ISSUE TITLE
SPLOTbox Media Collector - Video layout problem 

### ISSUE THREAD

**Issue by SezAndrewsMedia** [cogdog/splotbox#3]
Hi Alan, 

I wonder if you can help me with this matter please? I've just been creating an archive subdomain for all of DMLL's video content but the layout of the webpage doesn't seem to be functioning properly as the videos are in one column rather than three and change dimensions on other pages. I haven't changed the settings apart from the Splotbox options for visitors to submit media content to the archive and the homepage is set on lastest posts rather than static. If you could give me any suggestions as to why this is happening and how to fix it, that would be much appreciated! 🙂
Many thanks!

http://videos.dmllmedia.coventry.domains/

**Comment by cogdog** [comment]
That's because you are using an older version of the theme. Was it installed from the options in the Wordpress installer on Coventry?

There was an issue with the way the parent theme formed excerpts, and you are getting bits of HTML from your first few sentences that have tags that are not correctly closed.

If you are able to ftp files to your site, you can download the theme here and replace everything in /wp-content/theme/splotbox with the files in this GitHUb. You can also try [using this plugin](https://wordpress.org/plugins/easy-theme-and-plugin-upgrades/) that lets you upload a zip file to replace the theme there (note you will have to download the one from GitHub, unzip, change the name of the director from `splotbox-master` to `splotbox` and re-zip.

The other way to do this is to edit all your entries and make sure there is no HTML in the opening paragraph.

**Comment by SezAndrewsMedia** [comment]
Thank you for your help and advice, I've followed everything through and have successfully managed to get the website to work! 😄

**Comment by cogdog** [comment]
Looks great!
